# Generated by Django 3.2 on 2022-10-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
