# Generated by Django 3.2 on 2022-10-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0002_logs_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='created_at',
            new_name='log_created_at',
        ),
    ]
